fillName = '//input[@type="text"]'
fillEmail = '//input[@type="email"]'
fillPassword = '//input[@type="password"]'
fillPhone = '//input[@type="numeric"]'
buttonSubmit = '//button[@class="btn btn-primary"]'
errorRegisteredEmail = '//div[@class="alert alert-danger bg-danger text-white border-0 fade show mb-4"]'
errorFillEmail ='//span[@class="text-danger"]'
errorFillPassword ='//div[@class="alert alert-danger bg-danger text-white border-0 fade show mb-4"]'
errorFillPhone = '//span[text()[contains(.,"phone terlalu pendek.")]]'